<a href="https://colab.research.google.com/github/riyapalesha/SPPU-Data_Science_And_Big_Data_Analytics_Lab/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Descriptive Statistics : Measures of Central Tendancy and Variability

# PART 1
Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a dataset (age, income etc.) with numeric variables grouped by one of the qualitative (categorical) variable
For example, if your categorical variable is age groups and quantitative variable is income, then provide summary statistics of income grouped by the age groups. Create a list that contains a numeric value for each response to the categorical variable.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving income.csv to income.csv

In [ ]:
# importing required python libraries
import pandas as pd
import numpy as np

In [ ]:
orig_income_df=pd.read_csv("income.csv")
orig_income_df

     Unnamed: 0  age  income
0             0   49  946815
1             1   55  861096
2             2   27  185809
3             3   48  791043
4             4   23  988453
..          ...  ...     ...
195         195   38  768508
196         196   46  524485
197         197   30  251448
198         198   51  186821
199         199   59  591476

[200 rows x 3 columns]

In [ ]:
income_df=orig_income_df.copy()

In [ ]:
income_df.head()

   Unnamed: 0  age  income
0           0   49  946815
1           1   55  861096
2           2   27  185809
3           3   48  791043
4           4   23  988453

In [ ]:
income_df.tail()

     Unnamed: 0  age  income
195         195   38  768508
196         196   46  524485
197         197   30  251448
198         198   51  186821
199         199   59  591476

In [ ]:
missing_values_count=income_df.isnull().sum()
missing_values_count

Unnamed: 0    0
age           0
income        0
dtype: int64

# Method 1 (By making age groups)


age_ranges = [0, 18, 26, 36, 46, 56, income_df['age'].max() + 1]: This line defines the age ranges, similar to the previous code. The age ranges are specified as [0, 18, 26, 36, 46, 56, max_age + 1], where max_age is the maximum age in the 'age' column of the DataFrame income_df.

age_labels = ['Below 18', '18-25', '26-35', '36-45', '46-55', '56+']: This line defines the labels for each age range, just like before.

sample = pd.cut(income_df['age'], bins=age_ranges, labels=age_labels, right=False): This line applies the pd.cut() function to categorize the 'age' variable into the specified age ranges, just as you did earlier. The resulting categorical variable is stored in the sample variable.

grouped_data = income_df.groupby(sample): This line groups the DataFrame income_df based on the values in the sample variable. This creates a DataFrameGroupBy object named grouped_data, which represents the grouped data.

summary_stats = grouped_data['income'].agg(['mean', 'median', 'min', 'max', 'std']): This line calculates the summary statistics for the 'income' variable within each group. The .agg() method is applied to the 'income' column of the grouped_data object, specifying the desired aggregation functions ['mean', 'median', 'min', 'max', 'std']. The resulting summary statistics are stored in the summary_stats DataFrame

In [ ]:
age_ranges = [0, 18, 26, 36, 46, 56, income_df['age'].max() + 1]
age_labels = ['Below 18', '18-25', '26-35', '36-45', '46-55', '56+']

In [ ]:
sample = pd.cut(income_df['age'], bins=age_ranges, labels=age_labels, right=False)

In [ ]:
sample

0      46-55
1      46-55
2      26-35
3      46-55
4      18-25
       ...
195    36-45
196    46-55
197    26-35
198    46-55
199      56+
Name: age, Length: 200, dtype: category
Categories (6, object): ['Below 18' < '18-25' < '26-35' < '36-45' < '46-55' < '56+']

In [ ]:
grouped_data = income_df.groupby(sample)
for group_name, group_data in grouped_data:
    print(f"Age Group: {group_name}")
    print(group_data)
    print()

Age Group: Below 18
Empty DataFrame
Columns: [Unnamed: 0, age, income]
Index: []

Age Group: 18-25
     Unnamed: 0  age  income
4             4   23  988453
6             6   21   49726
9             9   25  801821
11           11   21  317420
13           13   22   45797
19           19   20  913832
22           22   24  276589
25           25   24  563352
27           27   25  809613
28           28   22  922526
31           31   21  306617
34           34   18  577483
37           37   20  380320
38           38   21  930850
40           40   19  443902
46           46   19   90842
47           47   20  438060
49           49   19   53193
50           50   23  407103
69           69   23  604625
70           70   21  125989
77           77   22  694767
79           79   23   78369
82           82   24  851512
91           91   23  565830
92           92   20  118591
98           98   22  496306
107         107   18  548534
116         116   25  724910
123         123   18  333185
124         124   21  354431
132         132   18  210523
150         150   18  717310
155         155   23  615829
156         156   24   45193
168         168   23  709024
171         171   24  564088
172         172   20  208683
182         182   23  431208
190         190   24   67924

Age Group: 26-35
     Unnamed: 0  age  income
2             2   27  185809
7             7   31  823583
10           10   34  180081
18           18   33  113683
24           24   30  554054
29           29   35  873197
41           41   29  149949
45           45   30  762230
54           54   31  650590
59           59   34  408370
66           66   26  321337
71           71   28  531716
73           73   27  839708
76           76   32  627875
78           78   34  214114
83           83   31  564202
86           86   30  783755
88           88   32  347800
89           89   34  305909
97           97   35  771862
104         104   26  969909
112         112   32  473290
114         114   33  737754
118         118   27  128383
120         120   29  613858
127         127   35  783524
129         129   32  776445
131         131   30  358927
140         140   33  271053
143         143   26  375869
146         146   34  819124
149         149   27  256750
157         157   35  393857
160         160   33  691930
162         162   31  785198
163         163   32  341235
176         176   31  520757
180         180   28  604415
181         181   33  383315
186         186   27  978108
197         197   30  251448

Age Group: 36-45
     Unnamed: 0  age  income
8             8   42  153768
14           14   41  149086
15           15   44  862593
17           17   38  847740
20           20   42  310850
26           26   38  541824
32           32   38  688413
36           36   42  284789
43           43   38  522546
51           51   45  796898
52           52   36  152283
57           57   36  459604
58           58   38  726686
67           67   44  531910
68           68   38  675283
75           75   45  813418
81           81   43  238628
87           87   42  792293
96           96   37  368608
100         100   42  339185
106         106   45  773902
113         113   40  274053
115         115   40  981575
117         117   36  991321
121         121   44  104688
125         125   40  478437
133         133   45  306885
134         134   39  895377
137         137   43  270200
138         138   39  896843
154         154   45  742897
159         159   36  650198
161         161   42  890956
174         174   45  785629
175         175   45  621446
177         177   40  480954
178         178   43  116031
179         179   45  897881
184         184   45  263806
187         187   36  520379
189         189   40  126951
191         191   43  929331
192         192   45  420266
195         195   38  768508

Age Group: 46-55
     Unnamed: 0  age  income
0             0   49  946815
1             1   55  861096
3             3   48  791043
5             5   50  421806
12           12   52   78410
21           21   49  357698
23           23   47  419968
30           30   46  352105
33           33   46   38983
42           42   55  173890
48           48   55   89180
53           53   54  663891
56           56   54  221143
60           60   51  620597
61           61   53  193698
62           62   49  110053
64           64   53  991203
65           65   49   80955
72           72   51  239632
74           74   51  565809
80           80   51  601378
90           90   46  504989
93           93   47  261153
94           94   48  343053
95           95   47  657523
99           99   53  783787
101         101   50  694686
102         102   51  900179
103         103   54   82499
108         108   54  498426
109         109   53  915861
110         110   48  331510
111         111   49  621301
119         119   48   56105
126         126   46  936544
130         130   49  851161
135         135   49  843938
139         139   50  698389
141         141   52  985485
142         142   47  584127
144         144   49  450653
145         145   50  559133
147         147   54  924925
151         151   46  638724
152         152   54  374204
164         164   55  455955
165         165   46  286599
167         167   53  184808
173         173   47  723209
183         183   51   68076
188         188   52  390280
196         196   46  524485
198         198   51  186821

Age Group: 56+
     Unnamed: 0  age  income
16           16   56  286657
35           35   57  133516
39           39   58  644846
44           44   57  506716
55           55   57   77428
63           63   57  575554
84           84   58  419345
85           85   57  369397
105         105   60  622818
122         122   56  522334
128         128   57  577183
136         136   57  139606
148         148   60   54699
153         153   58  171855
158         158   60  733348
166         166   57   92574
169         169   56  902663
170         170   56  922925
185         185   60  116156
193         193   59   94693
194         194   60  877738
199         199   59  591476

In [ ]:
summary_stats = grouped_data['income'].agg(['mean', 'median', 'min', 'max', 'std'])

In [ ]:
summary_stats

                   mean    median       min       max            std
age
Below 18            NaN       NaN       NaN       NaN            NaN
18-25     459608.250000  440981.0   45193.0  988453.0  288659.156205
26-35     524999.341463  531716.0  113683.0  978108.0  253198.445002
36-45     555566.340909  536867.0  104688.0  991321.0  278005.885392
46-55     493168.698113  498426.0   38983.0  991203.0  290851.540759
56+       428796.681818  463030.5   54699.0  922925.0  291029.485021

# Method 2 (Without grouping age)

In [ ]:
categorical_var='age'
summary_stats2= income_df.groupby(categorical_var).describe()

In [ ]:
summary_stats2

    Unnamed: 0                                                              \
         count        mean        std    min     25%    50%     75%    max
age
18         5.0  109.200000  44.818523   34.0  107.00  123.0  132.00  150.0
19         3.0   45.000000   4.582576   40.0   43.00   46.0   47.50   49.0
20         5.0   73.400000  61.337590   19.0   37.00   47.0   92.00  172.0
21         6.0   46.666667  44.207088    6.0   16.00   34.5   62.00  124.0
22         4.0   54.000000  40.091562   13.0   24.25   52.5   82.25   98.0
23         8.0   99.750000  62.759746    4.0   64.25   85.0  158.25  182.0
24         6.0  107.666667  74.776110   22.0   39.25  119.0  167.25  190.0
25         3.0   50.666667  57.291652    9.0   18.00   27.0   71.50  116.0
26         3.0  104.333333  38.501082   66.0   85.00  104.0  123.50  143.0
27         5.0  105.600000  71.234121    2.0   73.00  118.0  149.00  186.0
28         2.0  125.500000  77.074639   71.0   98.25  125.5  152.75  180.0
29         2.0   80.500000  55.861436   41.0   60.75   80.5  100.25  120.0
30         5.0   96.600000  69.478774   24.0   45.00   86.0  131.00  197.0
31         5.0   96.400000  71.779524    7.0   54.00   83.0  162.00  176.0
32         5.0  113.600000  34.457220   76.0   88.00  112.0  129.00  163.0
33         5.0  122.600000  63.496457   18.0  114.00  140.0  160.00  181.0
34         5.0   76.400000  49.287930   10.0   59.00   78.0   89.00  146.0
35         4.0  102.500000  54.781384   29.0   80.00  112.0  134.50  157.0
36         5.0  114.400000  60.114890   52.0   57.00  117.0  159.00  187.0
37         1.0   96.000000        NaN   96.0   96.00   96.0   96.00   96.0
38         7.0   62.714286  60.991022   17.0   29.00   43.0   63.00  195.0
39         2.0  136.000000   2.828427  134.0  135.00  136.0  137.00  138.0
40         5.0  143.800000  36.320793  113.0  115.00  125.0  177.00  189.0
41         1.0   14.000000        NaN   14.0   14.00   14.0   14.00   14.0
42         6.0   68.666667  58.239734    8.0   24.00   61.5   96.75  161.0
43         4.0  146.750000  49.506734   81.0  123.00  157.5  181.25  191.0
44         3.0   67.666667  53.003145   15.0   41.00   67.0   94.00  121.0
45        10.0  142.300000  49.481871   51.0  112.75  164.0  178.00  192.0
46         7.0  113.000000  64.580699   30.0   61.50  126.0  158.00  196.0
47         5.0  105.200000  56.922755   23.0   93.00   95.0  142.00  173.0
48         4.0   81.500000  53.344790    3.0   71.25  102.0  112.25  119.0
49         8.0   83.500000  54.659988    0.0   51.75   88.0  131.25  144.0
50         4.0   97.500000  64.670962    5.0   77.00  120.0  140.50  145.0
51         7.0  109.857143  56.681651   60.0   73.00   80.0  142.50  198.0
52         3.0  113.666667  91.128115   12.0   76.50  141.0  164.50  188.0
53         5.0  100.000000  42.976738   61.0   64.00   99.0  109.00  167.0
54         6.0  103.166667  42.593035   53.0   67.75  105.5  137.25  152.0
55         4.0   63.750000  70.020830    1.0   31.75   45.0   77.00  164.0
56         4.0  119.250000  72.384966   16.0   95.50  145.5  169.25  170.0
57         8.0   89.000000  48.473852   35.0   52.25   74.0  130.00  166.0
58         3.0   92.000000  57.419509   39.0   61.50   84.0  118.50  153.0
59         2.0  196.000000   4.242641  193.0  194.50  196.0  197.50  199.0
60         5.0  158.000000  35.121219  105.0  148.00  158.0  185.00  194.0

    income                                                               \
     count           mean            std       min        25%       50%
age
18     5.0  477407.000000  202888.368354  210523.0  333185.00  548534.0
19     3.0  195979.000000  215531.255847   53193.0   72017.50   90842.0
20     5.0  411897.200000  308603.585995  118591.0  208683.00  380320.0
21     6.0  347505.500000  310050.952382   49726.0  171146.00  312018.5
22     4.0  539849.000000  372569.744972   45797.0  383678.75  595536.5
23     8.0  550055.125000  262423.994513   78369.0  425181.75  585227.5
24     6.0  394776.333333  318967.354310   45193.0  120090.25  419970.5
25     3.0  778781.333333   46816.335101  724910.0  763365.50  801821.0
26     3.0  555705.000000  359745.951983  321337.0  348603.00  375869.0
27     5.0  477751.600000  399217.850955  128383.0  185809.00  256750.0
28     2.0  568065.500000   51405.955885  531716.0  549890.75  568065.5
29     2.0  381903.500000  328033.199753  149949.0  265926.25  381903.5
30     5.0  542082.800000  237185.679160  251448.0  358927.00  554054.0
31     5.0  668866.000000  132942.962644  520757.0  564202.00  650590.0
32     5.0  513329.000000  187729.946845  341235.0  347800.00  473290.0
33     5.0  439547.000000  269427.265646  113683.0  271053.00  383315.0
34     5.0  385519.600000  258097.686058  180081.0  214114.00  305909.0
35     4.0  705610.000000  212708.920419  393857.0  677360.75  777693.0
36     5.0  554757.000000  304925.553023  152283.0  459604.00  520379.0
37     1.0  368608.000000            NaN  368608.0  368608.00  368608.0
38     7.0  681571.428571  116982.953385  522546.0  608553.50  688413.0
39     2.0  896110.000000    1036.618541  895377.0  895743.50  896110.0
40     5.0  468394.000000  323251.102372  126951.0  274053.00  478437.0
41     1.0  149086.000000            NaN  149086.0  149086.00  149086.0
42     6.0  461973.500000  302468.928203  153768.0  291304.25  325017.5
43     4.0  388547.500000  366603.338720  116031.0  207978.75  254414.0
44     3.0  499730.333333  379975.848530  104688.0  318299.00  531910.0
45    10.0  642302.800000  229002.794936  263806.0  470561.00  758399.5
46     7.0  468918.428571  283909.187651   38983.0  319352.00  504989.0
47     5.0  529196.000000  187685.963575  261153.0  419968.00  584127.0
48     4.0  380427.750000  304181.934541   56105.0  262658.75  337281.5
49     8.0  532821.750000  337573.102105   80955.0  295786.75  535977.0
50     4.0  593503.500000  131529.754800  421806.0  524801.25  626909.5
51     7.0  454641.714286  296458.118592   68076.0  213226.50  565809.0
52     3.0  484725.000000  460853.726713   78410.0  234345.00  390280.0
53     5.0  613871.400000  394680.013833  184808.0  193698.00  783787.0
54     6.0  460848.000000  305325.944991   82499.0  259408.25  436315.0
55     4.0  395030.250000  348030.886599   89180.0  152712.50  314922.5
56     4.0  658644.750000  308946.847418  286657.0  463414.75  712498.5
57     8.0  308996.750000  222218.469316   77428.0  123280.50  254501.5
58     3.0  412015.333333  236580.672352  171855.0  295600.00  419345.0
59     2.0  343084.500000  351278.628078   94693.0  218888.75  343084.5
60     5.0  480951.800000  372839.299898   54699.0  116156.00  622818.0


           75%       max
age
18   577483.00  717310.0
19   267372.00  443902.0
20   438060.00  913832.0
21   345178.25  930850.0
22   751706.75  922526.0
23   639127.75  988453.0
24   563904.00  851512.0
25   805717.00  809613.0
26   672889.00  969909.0
27   839708.00  978108.0
28   586240.25  604415.0
29   497880.75  613858.0
30   762230.00  783755.0
31   785198.00  823583.0
32   627875.00  776445.0
33   691930.00  737754.0
34   408370.00  819124.0
35   805942.25  873197.0
36   650198.00  991321.0
37   368608.00  368608.0
38   747597.00  847740.0
39   896476.50  896843.0
40   480954.00  981575.0
41   149086.00  149086.0
42   679016.00  890956.0
43   434982.75  929331.0
44   697251.50  862593.0
45   794080.75  897881.0
46   581604.50  936544.0
47   657523.00  723209.0
48   455050.50  791043.0
49   845743.75  946815.0
50   695611.75  698389.0
51   610987.50  900179.0
52   687882.50  985485.0
53   915861.00  991203.0
54   622524.75  924925.0
55   557240.25  861096.0
56   907728.50  922925.0
57   523925.50  577183.0
58   532095.50  644846.0
59   467280.25  591476.0
60   733348.00  877738.0

# PART 2

Write a Python program to display some basic statistical details like percentile, mean, standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-virginica of iris.csv dataset.

In [ ]:
from google.colab import files
uploaded2=files.upload()

Saving Iris.csv to Iris.csv

In [ ]:
orig_iris_df=pd.read_csv("Iris.csv")

In [ ]:
iris_df=orig_iris_df.copy()

In [ ]:
iris_df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
iris_df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
iris_df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
iris_df.shape

(150, 6)

In [ ]:
missing_values_count =iris_df.isna().sum()
missing_values_count

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
iris_df["Species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
setosa=iris_df[iris_df["Species"] == 'Iris-setosa']
setosa

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [ ]:
versicolor=iris_df[iris_df["Species"] == 'Iris-versicolor']
versicolor

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
55,56,5.7,2.8,4.5,1.3,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
58,59,6.6,2.9,4.6,1.3,Iris-versicolor
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
61,62,5.9,3.0,4.2,1.5,Iris-versicolor
62,63,6.0,2.2,4.0,1.0,Iris-versicolor
63,64,6.1,2.9,4.7,1.4,Iris-versicolor
64,65,5.6,2.9,3.6,1.3,Iris-versicolor
65,66,6.7,3.1,4.4,1.4,Iris-versicolor
66,67,5.6,3.0,4.5,1.5,Iris-versicolor
67,68,5.8,2.7,4.1,1.0,Iris-versicolor
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
69,70,5.6,2.5,3.9,1.1,Iris-versicolor
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
71,72,6.1,2.8,4.0,1.3,Iris-versicolor
72,73,6.3,2.5,4.9,1.5,Iris-versicolor
73,74,6.1,2.8,4.7,1.2,Iris-versicolor
74,75,6.4,2.9,4.3,1.3,Iris-versicolor
75,76,6.6,3.0,4.4,1.4,Iris-versicolor
76,77,6.8,2.8,4.8,1.4,Iris-versicolor
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
78,79,6.0,2.9,4.5,1.5,Iris-versicolor
79,80,5.7,2.6,3.5,1.0,Iris-versicolor
80,81,5.5,2.4,3.8,1.1,Iris-versicolor
81,82,5.5,2.4,3.7,1.0,Iris-versicolor
82,83,5.8,2.7,3.9,1.2,Iris-versicolor
83,84,6.0,2.7,5.1,1.6,Iris-versicolor
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor
89,90,5.5,2.5,4.0,1.3,Iris-versicolor
90,91,5.5,2.6,4.4,1.2,Iris-versicolor
91,92,6.1,3.0,4.6,1.4,Iris-versicolor
92,93,5.8,2.6,4.0,1.2,Iris-versicolor
93,94,5.0,2.3,3.3,1.0,Iris-versicolor
94,95,5.6,2.7,4.2,1.3,Iris-versicolor
95,96,5.7,3.0,4.2,1.2,Iris-versicolor
96,97,5.7,2.9,4.2,1.3,Iris-versicolor
97,98,6.2,2.9,4.3,1.3,Iris-versicolor
98,99,5.1,2.5,3.0,1.1,Iris-versicolor
99,100,5.7,2.8,4.1,1.3,Iris-versicolor

In [ ]:
virginica=iris_df[iris_df["Species"] == 'Iris-virginica']
virginica

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
106,107,4.9,2.5,4.5,1.7,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
108,109,6.7,2.5,5.8,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
113,114,5.7,2.5,5.0,2.0,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
119,120,6.0,2.2,5.0,1.5,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
123,124,6.3,2.7,4.9,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
133,134,6.3,2.8,5.1,1.5,Iris-virginica
134,135,6.1,2.6,5.6,1.4,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
setosa.describe()

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [ ]:
versicolor.describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [ ]:
virginica.describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000

In [ ]:
categorical_var="Species"
summary_stats=iris_df.groupby(categorical_var).describe()
summary_stats

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]